 name: CI
 on: [push]
 jobs:
     build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Dependency Script
          run: bash dep.sh  
        - name: save jar file 
          uses: actions/upload-artifact@v4
          with:
            name: thymeleaf-jar     
            OUTPUT_PATH: tivy/outjar/thymeleafExample-0.0.1-SNAPSHOT.jar
