 name: CI
 on: [push]
 jobs:
     build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Dependency Script
          run: bash dep.sh  
        - name: Create output directory
          run: mkdir -p "outjar/jarfiles"
        - name: Upload JAR artifact 
          run: |
            OUTPUT_FILE="outjar/jarfiles/home/runner/.m2/repository/com/work/thymeleaf/work/0.0.1-SNAPSHOT/work-0.0.1-SNAPSHOT.jar-${DATE}.json"
            mkdir -p "outjar/jarfiles"